# Generated by Django 5.0.2 on 2024-11-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_produc_kategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produc',
            old_name='judul',
            new_name='nama_product',
        ),
    ]
