# Generated by Django 5.0.2 on 2024-11-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_judul_produc_nama_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='produc',
            name='harga',
            field=models.DecimalField(decimal_places=2, default='123', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produc',
            name='jumlah_product',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
